In [14]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [ ]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
method_name_replacer = {"uniform": "Uniform", 
                        "kmm": "KMM",
                        "psa": "PSA",
                        "soft-mrs-linear": "Soft-MRS",
                        "mrs-forest": "MRS",
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        }
data_set_replacer = {"diabetes": "Diabetes",
                    "folktables_employment": "Employment", 
                     "folktables_income": "Income",
                     "bank_marketing": "Bank Marketing",
                     "hr_analytics": "HR Analytic",
                     "german_credit": "German Credit", 
                     "breast_cancer": "Breast Cancer", 
                     "loan_prediction": "Loan",
                    }

In [ ]:
aurocs = []
auprcs = []
mccs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            json_file = result_path / dataset / bias_type /  "0.1"/ method / "classification_results.json"
            try:
                result_file = pd.read_json(str(json_file))
            except FileNotFoundError:
                continue
            dict_list.append(
                {
                    "Method": method, "Data Set": dataset, 
                    "AUROC Mean": result_file["random forest auroc"]["mean"], 
                    "AUROC Std": result_file["random forest auroc"]["sd"], 
                    "MCC Mean": result_file["random forest mcc"]["mean"], 
                    "MCC Std": result_file["random forest mcc"]["sd"], 
                    "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                    "AUPRC Std": result_file["random forest auprc"]["sd"], 
                    "Bias Type": bias_type, "Bias Strength": 0.1,
                    "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                    "Dropped Samples Std": result_file["dropped_samples"]["std"],
                }
                            )
result_df = pd.DataFrame(data=dict_list)

In [17]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,diabetes,0.791498,0.022072,0.371281,0.037717,less_positive_class,0.1,0.00,0.000000
1,KMM,diabetes,0.781169,0.021943,0.357066,0.041765,less_positive_class,0.1,0.00,0.000000
2,PSA,diabetes,0.787277,0.023148,0.367046,0.037046,less_positive_class,0.1,0.00,0.000000
3,Soft-MRS,diabetes,0.787917,0.021554,0.367637,0.037645,less_positive_class,0.1,0.00,0.000000
4,MRS,diabetes,0.788607,0.023040,0.367308,0.039618,less_positive_class,0.1,49.90,32.116818
5,FW-MRS,diabetes,0.783521,0.024444,0.359864,0.039249,less_positive_class,0.1,45.20,33.881558
6,FW-MRS$_{SVM}$,diabetes,0.781510,0.029975,0.355858,0.047168,less_positive_class,0.1,82.70,34.441400
7,Uniform,folktables_employment,0.870601,0.010491,0.826992,0.017307,less_positive_class,0.1,0.00,0.000000
8,KMM,folktables_employment,0.856631,0.013580,0.808776,0.021985,less_positive_class,0.1,0.00,0.000000
9,PSA,folktables_employment,0.867401,0.010937,0.823689,0.017363,less_positive_class,0.1,0.04,0.280000
10,Soft-MRS,folktables_employment,0.862420,0.012423,0.818201,0.019590,less_positive_class,0.1,0.00,0.000000
11,MRS,folktables_employment,0.869784,0.009878,0.825616,0.016272,less_positive_class,0.1,287.50,107.215904
12,FW-MRS,folktables_employment,0.868148,0.011183,0.824358,0.017503,less_positive_class,0.1,292.90,103.798314
13,FW-MRS$_{SVM}$,folktables_employment,0.863742,0.011632,0.818748,0.018774,less_positive_class,0.1,278.50,29.210443
14,Uniform,folktables_income,0.838084,0.012878,0.788634,0.020309,less_positive_class,0.1,0.00,0.000000
15,KMM,folktables_income,0.820208,0.014266,0.765446,0.019706,less_positive_class,0.1,0.00,0.000000
16,PSA,folktables_income,0.831057,0.013985,0.780822,0.021689,less_positive_class,0.1,0.16,0.703136
17,Soft-MRS,folktables_income,0.826917,0.013205,0.773737,0.019415,less_positive_class,0.1,0.00,0.000000
18,MRS,folktables_income,0.837289,0.012323,0.787584,0.019060,less_positive_class,0.1,274.50,80.611724
19,FW-MRS,folktables_income,0.836167,0.012495,0.787197,0.019151,less_positive_class,0.1,266.60,88.286126
20,FW-MRS$_{SVM}$,folktables_income,0.833326,0.012865,0.784087,0.018735,less_positive_class,0.1,299.50,30.385029
21,Uniform,bank_marketing,0.846908,0.021440,0.465787,0.051725,less_positive_class,0.1,0.00,0.000000
22,KMM,bank_marketing,0.831756,0.026469,0.445607,0.058065,less_positive_class,0.1,0.00,0.000000
23,PSA,bank_marketing,0.839479,0.025952,0.454844,0.048837,less_positive_class,0.1,0.00,0.000000
24,Soft-MRS,bank_marketing,0.834325,0.025744,0.446626,0.053698,less_positive_class,0.1,0.00,0.000000
25,MRS,bank_marketing,0.845264,0.021926,0.467804,0.052034,less_positive_class,0.1,62.90,34.030721
26,FW-MRS,bank_marketing,0.843134,0.020878,0.463003,0.052695,less_positive_class,0.1,61.30,29.254230
27,FW-MRS$_{SVM}$,bank_marketing,0.840364,0.023520,0.458200,0.051689,less_positive_class,0.1,63.20,35.139152
28,Uniform,hr_analytics,0.752772,0.018290,0.455071,0.029285,less_positive_class,0.1,0.00,0.000000
29,KMM,hr_analytics,0.749431,0.019074,0.449147,0.032049,less_positive_class,0.1,0.00,0.000000
30,PSA,hr_analytics,0.750453,0.019049,0.453771,0.034252,less_positive_class,0.1,0.00,0.000000
31,Soft-MRS,hr_analytics,0.751405,0.019091,0.453650,0.035232,less_positive_class,0.1,0.00,0.000000
32,MRS,hr_analytics,0.751456,0.019457,0.456013,0.030210,less_positive_class,0.1,107.40,53.630588
33,FW-MRS,hr_analytics,0.749695,0.022290,0.450022,0.038072,less_positive_class,0.1,107.10,54.836940
34,FW-MRS$_{SVM}$,hr_analytics,0.751479,0.018876,0.454417,0.033738,less_positive_class,0.1,173.00,71.596089
35,Uniform,german_credit,0.667239,0.053736,0.460906,0.064090,less_positive_class,0.1,0.00,0.000000
36,KMM,german_credit,0.648943,0.052757,0.443033,0.062464,less_positive_class,0.1,0.00,0.000000
37,PSA,german_credit,0.658996,0.055090,0.452393,0.063956,less_positive_class,0.1,0.00,0.000000
38,Soft-MRS,german_credit,0.656869,0.053348,0.450931,0.059935,less_positive_class,0.1,0.00,0.000000
39,MRS,german_credit,0.672495,0.051572,0.464485,0.066462,less_positive_class,0.1,13.60,10.584895
40,FW-MRS,german_credit,0.641964,0.060993,0.436181,0.064291,less_positive_class,0.1,9.20,10.740577
41,FW-MRS$_{SVM}$,german_credit,0.639449,0.065877,0.436267,0.068833,less_positive_class,0.1,11.40,12.001667
42,Uniform,breast_cancer,0.987591,0.006273,0.993799,0.003288,less_positive_class,0.1,0.00,0.000000
43,KMM,breast_cancer,0.989408,0.005247,0.994803,0.002604,less_positive_class,0.1,0.00,0.000000
44,PSA,breast_cancer,0.987893,0.006442,0.994015,0.003248,less_positive_class,0.1,0.00,0.000000
45,Soft-MRS,breast_cancer,0.988682,0.005525,0.994384,0.002774,less_positive_class,0.1,0.00,0.000000
46,MRS,breast_cancer,0.988590,0.005984,0.994571,0.002792,less_positive_class,0.1,53.06,6.807085
47,FW-MRS,breast_cancer,0.980853,0.012104,0.989371,0.007935,less_positive_class,0.1,41.50,11.360018
48,FW-MRS$_{SVM}$,breast_cancer,0.976959,0.014481,0.986823,0.009292,less_positive_class,0.1,50.12,11.320141
49,Uniform,loan_prediction,0.658389,0.080697,0.794671,0.050524,less_positive_class,0.1,0.00,0.000000
50,KMM,loan_prediction,0.610365,0.096952,0.776497,0.061962,less_positive_class,0.1,0.00,0.000000
51,PSA,loan_prediction,0.627560,0.095193,0.780323,0.058087,less_positive_class,0.1,0.00,0.000000
52,Soft-MRS,loan_prediction,0.619324,0.100184,0.779368,0.062878,less_positive_class,0.1,0.00,0.000000
53,MRS,loan_prediction,0.645463,0.085967,0.791333,0.053357,less_positive_class,0.1,8.12,5.105448
54,FW-MRS,loan_prediction,0.612471,0.081527,0.777703,0.051559,less_positive_class,0.1,4.58,4.157355
55,FW-MRS$_{SVM}$,loan_prediction,0.585903,0.097277,0.757215,0.061026,less_positive_class,0.1,4.82,4.188986

In [18]:
for bias_type in bias_types:
    for dataset in data_set_replacer.keys():
        mean_auroc_values = []
        std_auroc_values = []
        for method in result_df["Method"].unique():
            try:
                mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                mean_auroc_values.append(np.round(mean_auroc, 3))

                std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                std_auroc_values.append(np.round(std_auroc, 2))
            except IndexError:
                mean_auroc_values.append(0)
                std_auroc_values.append(0)

        print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
& ${mean_auroc_values[6]}\\pm{std_auroc_values[6]}$ & \
\\\\")
    print("\n")

Diabetes & $0.791\pm0.02$ & $0.781\pm0.02$ & $0.787\pm0.02$ & $0.788\pm0.02$ & $0.789\pm0.02$ & $0.784\pm0.02$ & $0.782\pm0.03$ & \\
Employment & $0.871\pm0.01$ & $0.857\pm0.01$ & $0.867\pm0.01$ & $0.862\pm0.01$ & $0.87\pm0.01$ & $0.868\pm0.01$ & $0.864\pm0.01$ & \\
Income & $0.838\pm0.01$ & $0.82\pm0.01$ & $0.831\pm0.01$ & $0.827\pm0.01$ & $0.837\pm0.01$ & $0.836\pm0.01$ & $0.833\pm0.01$ & \\
Bank Marketing & $0.847\pm0.02$ & $0.832\pm0.03$ & $0.839\pm0.03$ & $0.834\pm0.03$ & $0.845\pm0.02$ & $0.843\pm0.02$ & $0.84\pm0.02$ & \\
HR Analytic & $0.753\pm0.02$ & $0.749\pm0.02$ & $0.75\pm0.02$ & $0.751\pm0.02$ & $0.751\pm0.02$ & $0.75\pm0.02$ & $0.751\pm0.02$ & \\
German Credit & $0.667\pm0.05$ & $0.649\pm0.05$ & $0.659\pm0.06$ & $0.657\pm0.05$ & $0.672\pm0.05$ & $0.642\pm0.06$ & $0.639\pm0.07$ & \\
Breast Cancer & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.989\pm0.01$ & $0.981\pm0.01$ & $0.977\pm0.01$ & \\
Loan & $0.658\pm0.08$ & $0.61\pm0.1$ & $0.628\pm0.1$ & $0.619\pm0.1$ & $0.645\pm0.09$ & $0.612\pm0.08$ & $0.586\pm0.1$ & \\

In [23]:
for bias_type in bias_types:
    print(f"{bias_type}, {0.1}")
    for dataset in data_set_replacer.keys():
        mean_auprc_values = []
        std_auprc_values = []
        for method in result_df["Method"].unique():
            try:
                mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                mean_auprc_values.append(np.round(mean_auprc, 3))

                std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                std_auprc_values.append(np.round(std_auprc, 2))
            except IndexError:
                mean_auprc_values.append(0)
                std_auprc_values.append(0)

        print(f"{data_set_replacer[dataset]} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ \
& ${mean_auprc_values[5]}\\pm{std_auprc_values[5]}$ \
& ${mean_auprc_values[6]}\\pm{std_auprc_values[6]}$  \
& \\\\")
print("\n")

less_positive_class, 0.1
Diabetes & $0.371\pm0.04$ & $0.357\pm0.04$ & $0.367\pm0.04$ & $0.368\pm0.04$ & $0.367\pm0.04$ & $0.36\pm0.04$ & $0.356\pm0.05$  & \\
Employment & $0.827\pm0.02$ & $0.809\pm0.02$ & $0.824\pm0.02$ & $0.818\pm0.02$ & $0.826\pm0.02$ & $0.824\pm0.02$ & $0.819\pm0.02$  & \\
Income & $0.789\pm0.02$ & $0.765\pm0.02$ & $0.781\pm0.02$ & $0.774\pm0.02$ & $0.788\pm0.02$ & $0.787\pm0.02$ & $0.784\pm0.02$  & \\
Bank Marketing & $0.466\pm0.05$ & $0.446\pm0.06$ & $0.455\pm0.05$ & $0.447\pm0.05$ & $0.468\pm0.05$ & $0.463\pm0.05$ & $0.458\pm0.05$  & \\
HR Analytic & $0.455\pm0.03$ & $0.449\pm0.03$ & $0.454\pm0.03$ & $0.454\pm0.04$ & $0.456\pm0.03$ & $0.45\pm0.04$ & $0.454\pm0.03$  & \\
German Credit & $0.461\pm0.06$ & $0.443\pm0.06$ & $0.452\pm0.06$ & $0.451\pm0.06$ & $0.464\pm0.07$ & $0.436\pm0.06$ & $0.436\pm0.07$  & \\
Breast Cancer & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.989\pm0.01$ & $0.987\pm0.01$  & \\
Loan & $0.795\pm0.05$ & $0.776\pm0.06$ & $0.78\pm0.06$ & $0.779\pm0.06$ & $0.791\pm0.05$ & $0.778\pm0.05$ & $0.757\pm0.06$  & \\

In [ ]:
for bias_type in bias_types:
    print(f"{bias_type}, {0.1}")
    for dataset in data_set_replacer.keys():
        mean_mcc_values = []
        std_mcc_values = []
        for method in result_df["Method"].unique():
            try:
                mean_mcc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["MCC Mean"].iloc[0]
                mean_mcc_values.append(np.round(mean_mcc, 3))

                std_mcc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["MCC Std"].iloc[0]
                std_mcc_values.append(np.round(std_mcc, 2))
            except IndexError:
                mean_mcc_values.append(0)
                std_mcc_values.append(0)

        print(f"{data_set_replacer[dataset]} \
& ${mean_mcc_values[0]}\\pm{std_mcc_values[0]}$ \
& ${mean_mcc_values[1]}\\pm{std_mcc_values[1]}$ \
& ${mean_mcc_values[2]}\\pm{std_mcc_values[2]}$ \
& ${mean_mcc_values[3]}\\pm{std_mcc_values[3]}$ \
& ${mean_mcc_values[4]}\\pm{std_mcc_values[4]}$ \
& ${mean_mcc_values[5]}\\pm{std_mcc_values[5]}$ \
& ${mean_mcc_values[6]}\\pm{std_mcc_values[6]}$  \
& \\\\")
print("\n")

In [20]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,diabetes,0.791,0.022,0.371,0.038,less_positive_class,0.1,0.00,0.000
1,KMM,diabetes,0.781,0.022,0.357,0.042,less_positive_class,0.1,0.00,0.000
2,PSA,diabetes,0.787,0.023,0.367,0.037,less_positive_class,0.1,0.00,0.000
3,Soft-MRS,diabetes,0.788,0.022,0.368,0.038,less_positive_class,0.1,0.00,0.000
4,MRS,diabetes,0.789,0.023,0.367,0.040,less_positive_class,0.1,49.90,32.117
5,FW-MRS,diabetes,0.784,0.024,0.360,0.039,less_positive_class,0.1,45.20,33.882
6,FW-MRS$_{SVM}$,diabetes,0.782,0.030,0.356,0.047,less_positive_class,0.1,82.70,34.441
7,Uniform,folktables_employment,0.871,0.010,0.827,0.017,less_positive_class,0.1,0.00,0.000
8,KMM,folktables_employment,0.857,0.014,0.809,0.022,less_positive_class,0.1,0.00,0.000
9,PSA,folktables_employment,0.867,0.011,0.824,0.017,less_positive_class,0.1,0.04,0.280
10,Soft-MRS,folktables_employment,0.862,0.012,0.818,0.020,less_positive_class,0.1,0.00,0.000
11,MRS,folktables_employment,0.870,0.010,0.826,0.016,less_positive_class,0.1,287.50,107.216
12,FW-MRS,folktables_employment,0.868,0.011,0.824,0.018,less_positive_class,0.1,292.90,103.798
13,FW-MRS$_{SVM}$,folktables_employment,0.864,0.012,0.819,0.019,less_positive_class,0.1,278.50,29.210
14,Uniform,folktables_income,0.838,0.013,0.789,0.020,less_positive_class,0.1,0.00,0.000
15,KMM,folktables_income,0.820,0.014,0.765,0.020,less_positive_class,0.1,0.00,0.000
16,PSA,folktables_income,0.831,0.014,0.781,0.022,less_positive_class,0.1,0.16,0.703
17,Soft-MRS,folktables_income,0.827,0.013,0.774,0.019,less_positive_class,0.1,0.00,0.000
18,MRS,folktables_income,0.837,0.012,0.788,0.019,less_positive_class,0.1,274.50,80.612
19,FW-MRS,folktables_income,0.836,0.012,0.787,0.019,less_positive_class,0.1,266.60,88.286
20,FW-MRS$_{SVM}$,folktables_income,0.833,0.013,0.784,0.019,less_positive_class,0.1,299.50,30.385
21,Uniform,bank_marketing,0.847,0.021,0.466,0.052,less_positive_class,0.1,0.00,0.000
22,KMM,bank_marketing,0.832,0.026,0.446,0.058,less_positive_class,0.1,0.00,0.000
23,PSA,bank_marketing,0.839,0.026,0.455,0.049,less_positive_class,0.1,0.00,0.000
24,Soft-MRS,bank_marketing,0.834,0.026,0.447,0.054,less_positive_class,0.1,0.00,0.000
25,MRS,bank_marketing,0.845,0.022,0.468,0.052,less_positive_class,0.1,62.90,34.031
26,FW-MRS,bank_marketing,0.843,0.021,0.463,0.053,less_positive_class,0.1,61.30,29.254
27,FW-MRS$_{SVM}$,bank_marketing,0.840,0.024,0.458,0.052,less_positive_class,0.1,63.20,35.139
28,Uniform,hr_analytics,0.753,0.018,0.455,0.029,less_positive_class,0.1,0.00,0.000
29,KMM,hr_analytics,0.749,0.019,0.449,0.032,less_positive_class,0.1,0.00,0.000
30,PSA,hr_analytics,0.750,0.019,0.454,0.034,less_positive_class,0.1,0.00,0.000
31,Soft-MRS,hr_analytics,0.751,0.019,0.454,0.035,less_positive_class,0.1,0.00,0.000
32,MRS,hr_analytics,0.751,0.019,0.456,0.030,less_positive_class,0.1,107.40,53.631
33,FW-MRS,hr_analytics,0.750,0.022,0.450,0.038,less_positive_class,0.1,107.10,54.837
34,FW-MRS$_{SVM}$,hr_analytics,0.751,0.019,0.454,0.034,less_positive_class,0.1,173.00,71.596
35,Uniform,german_credit,0.667,0.054,0.461,0.064,less_positive_class,0.1,0.00,0.000
36,KMM,german_credit,0.649,0.053,0.443,0.062,less_positive_class,0.1,0.00,0.000
37,PSA,german_credit,0.659,0.055,0.452,0.064,less_positive_class,0.1,0.00,0.000
38,Soft-MRS,german_credit,0.657,0.053,0.451,0.060,less_positive_class,0.1,0.00,0.000
39,MRS,german_credit,0.672,0.052,0.464,0.066,less_positive_class,0.1,13.60,10.585
40,FW-MRS,german_credit,0.642,0.061,0.436,0.064,less_positive_class,0.1,9.20,10.741
41,FW-MRS$_{SVM}$,german_credit,0.639,0.066,0.436,0.069,less_positive_class,0.1,11.40,12.002
42,Uniform,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.00,0.000
43,KMM,breast_cancer,0.989,0.005,0.995,0.003,less_positive_class,0.1,0.00,0.000
44,PSA,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.00,0.000
45,Soft-MRS,breast_cancer,0.989,0.006,0.994,0.003,less_positive_class,0.1,0.00,0.000
46,MRS,breast_cancer,0.989,0.006,0.995,0.003,less_positive_class,0.1,53.06,6.807
47,FW-MRS,breast_cancer,0.981,0.012,0.989,0.008,less_positive_class,0.1,41.50,11.360
48,FW-MRS$_{SVM}$,breast_cancer,0.977,0.014,0.987,0.009,less_positive_class,0.1,50.12,11.320
49,Uniform,loan_prediction,0.658,0.081,0.795,0.051,less_positive_class,0.1,0.00,0.000
50,KMM,loan_prediction,0.610,0.097,0.776,0.062,less_positive_class,0.1,0.00,0.000
51,PSA,loan_prediction,0.628,0.095,0.780,0.058,less_positive_class,0.1,0.00,0.000
52,Soft-MRS,loan_prediction,0.619,0.100,0.779,0.063,less_positive_class,0.1,0.00,0.000
53,MRS,loan_prediction,0.645,0.086,0.791,0.053,less_positive_class,0.1,8.12,5.105
54,FW-MRS,loan_prediction,0.612,0.082,0.778,0.052,less_positive_class,0.1,4.58,4.157
55,FW-MRS$_{SVM}$,loan_prediction,0.586,0.097,0.757,0.061,less_positive_class,0.1,4.82,4.189

In [ ]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.round(3).groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df["Rank MCC"] = result_df.round(3).groupby("Data Set")["MCC Mean"].rank(ascending=False)
result_df[["Method", "Rank AUROC", "Rank AUPRC", "Rank MCC"]].groupby("Method").mean()

                Rank AUROC  Rank AUPRC
Method
FW-MRS              4.5625      4.7500
FW-MRS$_{SVM}$      5.3750      5.5625
KMM                 6.0000      5.8125
MRS                 2.0000      1.7500
PSA                 4.2500      3.8750
Soft-MRS            4.2500      4.5000
Uniform             1.5625      1.7500