In [1]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [2]:
result_path = Path("../results/decomposition")
bias_types = ["less_positive_class"]
less_bias_strengths = ["0.1"]
method_name_replacer = {
    "uniform": "Uniform", 
    "kmm": "KMM",
    "psa": "PSA",
    "soft-mrs-linear": "Soft-MRS",
    "mrs-forest": "MRS", 
    "fw-mrs-temperature": "FW-MRS-RF",
    "fw-mrs-temperature-svm": "FW-MRS-SVM", 
                      }
data_set_replacer = {
    "diabetes": "Diabetes",
    "folktables_employment": "Employment",
    "folktables_income": "Income",
    "bank_marketing": "Bank Marketing",
    "hr_analytics": "HR Analytic",
    "german_credit": "German Credit",
    "breast_cancer": "Breast Cancer",
    "loan_prediction": "Loan",
    }

In [3]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "bias_variance_decomposition.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                        "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [4]:
result_df = result_df.replace(method_name_replacer)
result_df = result_df.replace(data_set_replacer)
result_df

,Method,Data Set,0-1 Bias,0-1 Variance,Bias Type,Bias Strength
0,Uniform,Diabetes,0.135000,0.076160,less_positive_class,0.1
1,KMM,Diabetes,0.135000,0.053230,less_positive_class,0.1
2,PSA,Diabetes,0.135000,0.093670,less_positive_class,0.1
3,Soft-MRS,Diabetes,0.135000,0.083250,less_positive_class,0.1
4,MRS,Diabetes,0.135000,0.070310,less_positive_class,0.1
5,FW-MRS-RF,Diabetes,0.135000,0.080470,less_positive_class,0.1
6,FW-MRS-SVM,Diabetes,0.135000,0.084280,less_positive_class,0.1
7,Uniform,Employment,0.211500,0.157220,less_positive_class,0.1
8,KMM,Employment,0.261500,0.200220,less_positive_class,0.1
9,PSA,Employment,0.212500,0.143360,less_positive_class,0.1
10,Soft-MRS,Employment,0.211500,0.154620,less_positive_class,0.1
11,MRS,Employment,0.216000,0.159530,less_positive_class,0.1
12,FW-MRS-RF,Employment,0.229000,0.148400,less_positive_class,0.1
13,FW-MRS-SVM,Employment,0.224500,0.161470,less_positive_class,0.1
14,Uniform,Income,0.292000,0.133660,less_positive_class,0.1
15,KMM,Income,0.252000,0.256330,less_positive_class,0.1
16,PSA,Income,0.288000,0.217420,less_positive_class,0.1
17,Soft-MRS,Income,0.238500,0.265320,less_positive_class,0.1
18,MRS,Income,0.277500,0.132740,less_positive_class,0.1
19,FW-MRS-RF,Income,0.291000,0.142530,less_positive_class,0.1
20,FW-MRS-SVM,Income,0.285500,0.140600,less_positive_class,0.1
21,Uniform,Bank Marketing,0.116000,0.013570,less_positive_class,0.1
22,KMM,Bank Marketing,0.116000,0.034080,less_positive_class,0.1
23,PSA,Bank Marketing,0.116000,0.027100,less_positive_class,0.1
24,Soft-MRS,Bank Marketing,0.116000,0.014100,less_positive_class,0.1
25,MRS,Bank Marketing,0.116000,0.013730,less_positive_class,0.1
26,FW-MRS-RF,Bank Marketing,0.116000,0.013050,less_positive_class,0.1
27,FW-MRS-SVM,Bank Marketing,0.116000,0.012480,less_positive_class,0.1
28,Uniform,HR Analytic,0.165494,0.071638,less_positive_class,0.1
29,KMM,HR Analytic,0.164824,0.157387,less_positive_class,0.1
30,PSA,HR Analytic,0.165494,0.109092,less_positive_class,0.1
31,Soft-MRS,HR Analytic,0.165494,0.170988,less_positive_class,0.1
32,MRS,HR Analytic,0.155109,0.089300,less_positive_class,0.1
33,FW-MRS-RF,HR Analytic,0.165494,0.075390,less_positive_class,0.1
34,FW-MRS-SVM,HR Analytic,0.165494,0.071424,less_positive_class,0.1
35,Uniform,German Credit,0.299401,0.013653,less_positive_class,0.1
36,KMM,German Credit,0.299401,0.020120,less_positive_class,0.1
37,PSA,German Credit,0.299401,0.024671,less_positive_class,0.1
38,Soft-MRS,German Credit,0.299401,0.023174,less_positive_class,0.1
39,MRS,German Credit,0.299401,0.020120,less_positive_class,0.1
40,FW-MRS-RF,German Credit,0.299401,0.017066,less_positive_class,0.1
41,FW-MRS-SVM,German Credit,0.299401,0.036766,less_positive_class,0.1
42,Uniform,Breast Cancer,0.048246,0.103947,less_positive_class,0.1
43,KMM,Breast Cancer,0.030702,0.077193,less_positive_class,0.1
44,PSA,Breast Cancer,0.035088,0.039912,less_positive_class,0.1
45,Soft-MRS,Breast Cancer,0.039474,0.057807,less_positive_class,0.1
46,MRS,Breast Cancer,0.035088,0.017281,less_positive_class,0.1
47,FW-MRS-RF,Breast Cancer,0.043860,0.055263,less_positive_class,0.1
48,FW-MRS-SVM,Breast Cancer,0.039474,0.051842,less_positive_class,0.1
49,Uniform,Loan,0.693750,0.066125,less_positive_class,0.1
50,KMM,Loan,0.693750,0.091000,less_positive_class,0.1
51,PSA,Loan,0.693750,0.063875,less_positive_class,0.1
52,Soft-MRS,Loan,0.693750,0.096375,less_positive_class,0.1
53,MRS,Loan,0.693750,0.066375,less_positive_class,0.1
54,FW-MRS-RF,Loan,0.693750,0.091500,less_positive_class,0.1
55,FW-MRS-SVM,Loan,0.693750,0.082250,less_positive_class,0.1

In [5]:
data_set_replacer.values()

dict_values(['Diabetes', 'Employment', 'Income', 'Bank Marketing', 'HR Analytic', 'German Credit', 'Breast Cancer', 'Loan'])

In [6]:
for bias_type in bias_types:
    bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        for dataset in data_set_replacer.values():
            bias_01_values = []
            for method in result_df["Method"].unique():
                bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
                bias_01_values.append(round(bias_01, 3))


            print(f"{dataset} \
& {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} \
& {bias_01_values[5]} & {bias_01_values[6]}  & \\\\")
        print("\n")

Diabetes & 0.135 & 0.135 & 0.135 & 0.135 & 0.135 & 0.135 & 0.135  & \\
Employment & 0.212 & 0.262 & 0.213 & 0.212 & 0.216 & 0.229 & 0.224  & \\
Income & 0.292 & 0.252 & 0.288 & 0.239 & 0.278 & 0.291 & 0.286  & \\
Bank Marketing & 0.116 & 0.116 & 0.116 & 0.116 & 0.116 & 0.116 & 0.116  & \\
HR Analytic & 0.165 & 0.165 & 0.165 & 0.165 & 0.155 & 0.165 & 0.165  & \\
German Credit & 0.299 & 0.299 & 0.299 & 0.299 & 0.299 & 0.299 & 0.299  & \\
Breast Cancer & 0.048 & 0.031 & 0.035 & 0.039 & 0.035 & 0.044 & 0.039  & \\
Loan & 0.694 & 0.694 & 0.694 & 0.694 & 0.694 & 0.694 & 0.694  & \\

In [7]:
for bias_type in bias_types:
    bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.values():
            variance_01_values = []
            for method in result_df["Method"].unique():
                variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
                variance_01_values.append(np.round(variance_01, 3))

            print(f"{dataset} \
& {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & {variance_01_values[5]} & {variance_01_values[6]} &\\\\")
        print("\n")

less_positive_class, 0.1
Diabetes & 0.076 & 0.053 & 0.094 & 0.083 & 0.07 & 0.08 & 0.084 &\\
Employment & 0.157 & 0.2 & 0.143 & 0.155 & 0.16 & 0.148 & 0.161 &\\
Income & 0.134 & 0.256 & 0.217 & 0.265 & 0.133 & 0.143 & 0.141 &\\
Bank Marketing & 0.014 & 0.034 & 0.027 & 0.014 & 0.014 & 0.013 & 0.012 &\\
HR Analytic & 0.072 & 0.157 & 0.109 & 0.171 & 0.089 & 0.075 & 0.071 &\\
German Credit & 0.014 & 0.02 & 0.025 & 0.023 & 0.02 & 0.017 & 0.037 &\\
Breast Cancer & 0.104 & 0.077 & 0.04 & 0.058 & 0.017 & 0.055 & 0.052 &\\
Loan & 0.066 & 0.091 & 0.064 & 0.096 & 0.066 & 0.092 & 0.082 &\\

In [8]:
result_df["Rank Bias"] = result_df.round(3).groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.round(3).groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF      4.8125         3.3750
FW-MRS-SVM     4.2500         3.8750
KMM            3.8125         5.1875
MRS            3.3125         2.8750
PSA            3.8750         4.1250
Soft-MRS       3.4375         5.3750
Uniform        4.5000         3.1875